version: '3.1'

services:
  megacmd:
    build: ./MEGAcmd
    stdin_open: true
    volumes:
      - sync-contents:/data

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data_postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRE_USER}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - db_data_pgadmin:/var/lib/pgadmin

  feathersjs:
    build: ./server
    ports:
      - "3030:3030"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/

  react:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules/
    stdin_open: true


  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  sync-contents:
  db_data_postgres:
  db_data_pgadmin: